---
- name: Implement docker compose using ansible
  hosts: all
  tasks:
    - name: Create mysql container
      docker_container:
        name: myavddb
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: test123
    - name: Create wordpress container
      docker_container:
        name: myavdword
        image: wordpress
        ports:
          - 8090:80
        links:
          myavddb:mysql
...
